### ISSUE TITLE
Unable to auth due to OAuth 2.0 policies

### ISSUE THREAD

**Issue by NightMean** [MarcelRobitaille/bbyen#14]
Hey, it's me again haha. 

It seems Google changed their policy and bbyen no longer runs or at least I'm unable to do re-auth. 
Any possibility to comply with their new policy? 

[OAuth 2.0 Policies](https://developers.google.com/identity/protocols/oauth2/policies#secure-response-handling)

![image](https://user-images.githubusercontent.com/5726996/189524447-b0620895-a27f-48d7-ac9e-d1dc6cf87523.png)

**Comment by MarcelRobitaille** [comment]
Hi @NightMean. Thanks for reporting this. I read through the page you linked and I didn't really see anything that I thought would apply.

One thing that sticks out to me is your redirect_uri: http://localhost:undefined/authorization_code. Have you specified a port correctly in the configuration file? It might just be that tripping Google up.

**Comment by NightMean** [comment]
I apologize.. you're correct. 
When I updated bbyen I did auth on my PC and then copied the token but kept the old config file which did not have the port in it.  
Everything works once again.
Thanks for the heads up.
