### ISSUE TITLE
Subscriptions list changing

### ISSUE THREAD

**Issue by kagejohn** [MarcelRobitaille/bbyen#2]
I am subscribed to 120 channels, and it looks like i have the activityType === "All" on 100.
But it keeps removing and readding them to the database, the first 82 is in the original position but after that it skips 262 and that gap seems to be getting larger every time it runs.

The console log also has them being added as new most times, i haven't subscribed or unsubscribed to any channel since i ran it the first time.

**Comment by MarcelRobitaille** [comment]
So, to confirm, `select count(id) from subscriptions;` gives 120, but `select max(id) from subscriptions;` is 262? Similar situation for me actually. Looking into it.

**Comment by MarcelRobitaille** [comment]
Do you have any logs you could share?

**Comment by kagejohn** [comment]
> So, to confirm, select count(id) from subscriptions; gives 120

No, the last 20 is skipped:
https://github.com/MarcelRobitaille/bbyen/blob/8d46e87675d7b6209243ac1a19640b8ddb4504f4/src/subscriptions.js#L24

The database have 100 subscriptions in it but after id 82 the next have id 374, and then it randomly skip numbers, the last have id 398

> Do you have any logs you could share?

Not that i know off, but:
![Screenshot_1](https://user-images.githubusercontent.com/9349493/94996671-5002c180-05a6-11eb-805d-1081f1583448.png)

**Comment by MarcelRobitaille** [comment]
Ok, same thing over here. I'm on it.

**Comment by MarcelRobitaille** [comment]
Looks like it's fixed in acc1c100ff6a78d9a6ace7efee5e7cb4b90b3c5e. It was a mix of something really stupid on my part and something really stupid on Google's part.
