### ISSUE TITLE
Service exits upon reaching email quota

### ISSUE THREAD

**Issue by Jozko568** [MarcelRobitaille/bbyen#23]
Hi! 

Recently I purged my installation and I'm setting up bbyen once again that I'm running as a service on Ubuntu machine. 
Upon checking for videos, I noticed that the service has exited as the email quota has run out. 
Can this be changed to e.g. wait 5 minutes and then try again instead of exiting? 
As bbyen doesn't send any notification, I only found this after couple of hours when I didn't receive anything in the mailbox. 

I think that it continued checking before instead of exiting, no? 

```
Dec 29 14:22:18 ubuntu npm[968725]: 2024-12-29T13:22:18.841Z [verbose] [videos]: New video from Freethink (id: 72DfLQlcdnM):
Dec 29 14:22:18 ubuntu npm[968725]: 2024-12-29T13:22:18.902Z [warn] [videos]: Email quota has run out.
Dec 29 14:22:18 ubuntu systemd[1]: bbyen.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 14:22:18 ubuntu systemd[1]: bbyen.service: Failed with result 'exit-code'.
```

**Comment by MarcelRobitaille** [comment]
You're right. This was the old behaviour. It was changed in 5870f28a25887e056b9aadb2f8ab0649e75c6421.
