### ISSUE TITLE
[error] [main]: Cannot read property 'client_id' of undefined

### ISSUE THREAD

**Issue by derolly** [MarcelRobitaille/bbyen#3]
When trying to start the application I always get the error: ```[error] [main]: Cannot read property 'client_id' of undefined```

My google-credentials.json looks like this:

```
{
    "web": {
        "client_id": "...",
        "project_id": "...",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "..."
    }
}
```

What do I miss?

Edit: I followed the instructions in you readme exactly and I'm using node version 14.15.0

**Comment by wampxs** [comment]
I am having the exact same problem.

**Comment by MarcelRobitaille** [comment]
This is a problem with your `google-credentials.json`. If you download the wrong file, it has "web" where it should have "installed".

My credentials looks like this:

```
{ "installed": {
    "client_id": ....,
    "project_id": ....,
    "auth_uri": ....,
    "token_uri": ....,
    "auth_provider_x509_cert_url": ....,
    "client_secret": .....,
    "redirect"uris": [...],
} }
```

I forget exactly why google sometimes gives "installed" and sometimes "web". The latter might be for running in browser if I had to guess. You could try changing "web" with "installed" in the config file and if that doesn't work try to download a credentials file with "installed" in it.

**Comment by wampxs** [comment]
So, this sorts it. By default, the credential page prompts to make it a Web App, to get the "installed" .json you have to set it as a computer app. Maybe specify that in the guide.

**Comment by MarcelRobitaille** [comment]
I forget actually. Is it # 2? 
![image](https://user-images.githubusercontent.com/8503756/100821789-11ab4680-341f-11eb-8a4c-8f80558903ab.png)

Since you just went through the steps, would you make a pull request?
