### ISSUE TITLE
Authorisation Error Error 403: access_denied

### ISSUE THREAD

**Issue by gamesbe** [MarcelRobitaille/bbyen#4]
Got as afar as to actually turn on the script, tried putting the url into chrome and get thrown this.

![image](https://user-images.githubusercontent.com/11790493/102778991-c49cff00-4350-11eb-8bcf-7579cfce5180.png)

**Comment by MarcelRobitaille** [comment]
Thanks for the report. I have never seen this before. The only thing I can recommend is to ensure that you put the correct url into your browser. To ensure that you downloaded the correct google credentials (#3). If nothing else works, wipe everything and try again. Sorry I couldn't be more helpful.

**Comment by L-S-H** [comment]
Have you ever solved this problem?

**Comment by ghost** [comment]
I also encountered this problem.
Have you ever solved this problem?

**Comment by ghost** [comment]
![Inked1_LI](https://user-images.githubusercontent.com/70587611/103454208-16686080-4d25-11eb-866e-51e6759c66b7.jpg)

Solve this

**Comment by MarcelRobitaille** [comment]
I'm going to close this for now. If you are still experiencing this, please re-open.
