### ISSUE TITLE
Missing Google APIs

### ISSUE THREAD

**Issue by ghost** [MarcelRobitaille/bbyen#5]
After running project through Node.js I get an error

https://i.gyazo.com/5abc2cf5c916898da85da5c152bc61e9.png

After installing googleapis and parse-duration with npm

I get this 

https://i.gyazo.com/5f52f5d81485474f4138b8d52ff2e47e.png

**Comment by itsLazR** [comment]
After installing googleapis with 
'npm install googleapis'

I get this https://i.gyazo.com/c65a960bf195be59cf6d9fdcba0b8bbd.png

**Comment by ghost** [comment]
You should add in requirements you need
googleapis
parse-duration
sqlite

however npm install'ing all of those fix it

**Comment by MarcelRobitaille** [comment]
These dependencies are in the package.json [here](https://github.com/MarcelRobitaille/bbyen/blob/master/package.json#L26), [here](https://github.com/MarcelRobitaille/bbyen/blob/master/package.json#L28), and [here](https://github.com/MarcelRobitaille/bbyen/blob/master/package.json#L32). Did you you run `npm install --production` as instructed [here](https://github.com/MarcelRobitaille/bbyen#installation-and-setup)?

Also, to run it, it's [`node src/index.js`](https://github.com/MarcelRobitaille/bbyen#running) not `node src/index/js` like in your image.

**Comment by ghost** [comment]
I eventually fixed it, not sure why `npm install --production` didn't install the dependencies the first time.
After getting it up, it is emailing me the [last 15 videos of all my subscriptions](https://i.gyazo.com/190a1a0528fde27e7e238ed8c9139f23.png) then getting timed out due to email quota limit. Is this normal? After doing this for all my subs will it only send emails for new videos being posted?

**Comment by MarcelRobitaille** [comment]
Yes, that is normal. BBYEN has no way of knowing which videos you already watched / got an official noreply@youtube.com email for. It just goes through the RSS feed for your subscription, and seeing as all the videos are new to it (on the first run), sends an email about each one. Note that the RSS feed from youtube only shows latest videos, so BBYEN doesn't send emails for videos back to the beginning of time, which is kind of a good thing and kind of a bad thing.

Once emails have been sent out for the entire backlog, you will only get notified about new videos.
